version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://bimo:bimo@db:5432/pdf
      - JWT_SECRET_KEY=bimo_secret_key

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: bimo
      POSTGRES_PASSWORD: bimo
      POSTGRES_DB: pdf
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
