"""empty message

Revision ID: 09816de068fc
Revises: 
Create Date: 2024-08-25 13:22:18.927584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09816de068fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=True),
    sa.Column('password_hash', sa.String(length=190), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('phone', sa.String(length=190), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('pdfs',
    sa.Column('id_pdf', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_pdf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdfs')
    op.drop_table('users')
    # ### end Alembic commands ###
